### ISSUE TITLE
Sorry  for that delay :-)

### ISSUE THREAD

**Issue by Luxo736** [UOA-MEDSCI-736/kdea020-metabolomics#2]
Title :  I do not  have clear what is SGA maybe avoid abbreviations in title  would be better ot put it into ().

Field research:  I think would be  good if you add also the number  there was a link where you can check that information.(  I consider only number  but maybe i will add both).

Data contact: i dont know if you  have the same problem than me  but  several articles  have several data contacts. My supervisor advice to consider each one that must be write in each article. (if that is your case).

ORCID : you might  found that info in the UNI web site. As each of them make public that information. At least a try might have outcomes.

Storage location: the cloud could be good , however  you might consider other options if you ask to the research department of the library.

Metadata: I am not so clear with this  matter. As  my supervisor consider  what is related to the previous information. However you add the features of the software that you will use. Honestly not very clear for me. So can’t say much.

Licencing: not sure if you public raw data via git. Then it could be still consider as a publication? As the information is possible to read?. Not sure at all.

Responsible for Data management : i imagine is only you as you re the only one that manage it. In my case  I didnt consider my supervisors.

**Comment by kdea020** [comment]
Thanks for that Luis! Very helpful. Will read through again carefully and make some changes - will let you know when they're done and you can tell me if you think it is improved?

**Comment by Luxo736** [comment]
Hi dear Kieran:

awesome ! great job, you are an inspiration!!!

good job mate .

Luis-Miguel

**Comment by kdea020** [comment]
Hey Luis,

I've made the changes that you and Ahmed suggest to my DMP. Still waiting on the pull request to be merged, but in the mean time you can read it here:

https://github.com/kdea020/kdea020-metabolomics/blob/master/kdea020-DMP-MedSci736-2016.docx

and tell me if that meets your standards for the final handshake :) Many thanks!
