### ISSUE TITLE
DMP REV

### ISSUE THREAD

**Issue by Adamthe1st** [UOA-MEDSCI-736/kdea020-metabolomics#3]
Dear Keirn  (I hope i spelled your name correctly)

Excellent and informative DMP you got here. Just a few comments:
1. **Title and Description**: 
   Nice and straight to the point! reading your description, I was able to have a general idea of what your field of research project and what platform you will use to examine and evaluate your  metabolomic data. However I did not understand what SGA in your title meant as it was not defined in the description. 
2.  **Project contributors:**
   Great! All sufficient details are there, however perhaps you could suggest ORCID to your supervisors.
3. **Policies and guidance:**
   I like how you provided the link for the UOA's  Researcher Code of Conduct. I think I will do that too. 
4. **Ethics and privacy:**
   I have a clear understanding about where you got your data from, and what would you intend to do with it. And what would happen in the case of publication. Good work!
5. **Data collection/ creation:**
   You have provided a nice and informative description of the nature, format and size of your data and where it will be stored and how it might be reused. Good work.

Overall, I think you have a very organized and goal-directed DMP. I would definitely try to improve my DMP into one like yours! Keep up the good work

Ahmed

**Comment by kdea020** [comment]
Thank you very much for your feedback, Ahmed :) Close, it just needs an 'a' and for the 'i' and the 'e' to be swapped, hahaha ("Kieran").

Will make some changes in line with your feedback (and Luis', who raised a couple of the same points as you!) and let you know when they're done (and what they were). Then we can have a discussion about the improvements and final sign-off?

**Comment by Adamthe1st** [comment]
Sounds great "K i e ran"! spelling noted :)

**Comment by Adamthe1st** [comment]
Dear Kieran, 

Just wondering if you have amended the changes to your DMP so that we could have a final handshake on that? 

Cheers 
Ahmed

**Comment by kdea020** [comment]
Hi Ahmed,

I have amended the changes to the DMP in line with your and Luis' feedback! It's still waiting for the pull request to be merged, but you'll be able to see it in the meantime at

https://github.com/kdea020/kdea020-metabolomics/blob/master/kdea020-DMP-MedSci736-2016.docx

and decide if that meets your requirements for the final handshake.

Thanks a lot! :)

**Comment by Adamthe1st** [comment]
Hi Kieran, 

Great changes you have made with your DMP!

Good luck with the final report :)

Ahmed
