### ISSUE TITLE
Code Peer Review

### ISSUE THREAD

**Issue by BibianaLee** [UOA-MEDSCI-736/kdea020-metabolomics#7]
Hi Kieran, 
Sorry for the late review! 

main_0-3.R, 
TESTING.R
project_0-2.R 

Although I found your code a little overwhelming,  all three files were well commented and done (I think) in a logical and sound manner. The main_0-3 R file in particular was thorough and presented in a easy to read style. It was also good to see licensing information as well as citations in this file. (I should probably include this info in my code as well) 

The only thing now would be to clean up some of your comments in the other files but you're still working on them so that's understandable. 

Just out of curiosity is there a reason why you have three separate files?

Overall, you seem to have put in a lot of time and effort into you code and it looks awesome :) Good job!!

**Comment by kdea020** [comment]
Hi Bibiana,
Thanks for your review!

I have added some more comments and cleaned up others, and also added EVEN MORE files (hahaha). I have multiple files as the functions in the program are modular, and sorting them by theme into individual scripts (which are then run from the main script) makes it much easier to read and edit (both for me and others).

Eagerly await your final handshake (or further feedback if you think it needs more changes!)

**Comment by BibianaLee** [comment]
I'm happy with the changes you've made :) closing the issue now!
